sudo: false
language: python
notifications:
  email: false
python:
  - pypy
  - 3.7-dev
  - 3.6
  - 3.5
  - 3.4
  - 2.7
before_install:
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
